##E Commerce website using python task-1
##In Python using:
##1) function
##2) print()
##3) If-elif-else.

## CONTINUATION1 CODE START##
def chkcontinue1():
    ans1 = input("Types yes to continue shopping or no to logout?\n").upper()
    
    if ans1 == "YES" or ans1 == "Y":
        ecommweb()

    elif ans1 == "NO" or ans1 == "N":
        print("Logged out successful!")

    else:
        print(" ")
        print("Invalid choice!")
        print("Please try again!")
        print(" ")
        chkcontinue1()
## CONTINUATION1 CODE END##
        
##CONITNUATION2 LOGIN CODE START##
def chkcontinue2():
    ans2 = input("Types yes to try again or type no to end program!\n").upper()
    if ans2 == "YES":
        logincode()

    elif ans2 == "NO":
        print("Program Ended!!")


    else:
        print(" ")
        print("Invalid choice! please try again!")
        chkcontinue2()
##CONTINUATION2 LOGIN CODE END##
        

## LOGIN CODE START##
def logincode():
    print("~~~"*15)
    print("~ Login Using emailid or phone number ~")
    Login = input("login id: ")
    Password = input("Password: ")
    
    if Login == "mananhakani@gmail.com" or Login == "Manan hakani" or Login == "Manan Hakani" or Login == "mananhakani" or Login == "9967250717":
        if Password == "manan":
            print("~~~"*15)
            print("\tLogin Successful\t")
            print("~~~"*15)
            print(" ")
            ecommweb()

        else:
            print("~~~"*15)
            print("Incorrect Password!")
            print("~~~"*15)
            chkcontinue2()

    else:
        print("~~~"*15)
        print("Incorrect Email id or password!")
        print("~~~"*15)
        chkcontinue2()
##LOGIN CODE END##

### BUY/CART CODE LOOP START##
def buycart():
    catog5 = input("Select Option:\n").upper()
    print(" ")

    if catog5 == "A":
        print("~~~~"*10)
        print("THANK YOU FOR THE PURACHSE!")
        print("CHECK OUT MORE OFFERS!")
        print("~~~~"*10)
        print(" ")
        chkcontinue1()

    elif catog5 == "B":
        print("Product has been added to your cart")
        chkcontinue1()

    else:
        print("Invalid Option! Product couldnt be purchased")
        chkcontinue1()

        
## BUY/CART CODE LOOP END##
        
## WEBSITE/PRODUCT CODE START##
def ecommweb():
        print("~~~~~"*10)
        print("Welcome, Manan Hakani To The Biggest Laptops Online Shop!")
        print("TOP BRANDS AT BEST PRICES")
        print("~~~~~"*10)
        print(" ")

        print("Get Started!")
        cat1 = "(A)SHOW LAPTOPS"
        cat2 = "(B)ACCOUNT DETAILS"
        print(cat1,end=" ")
        print(cat2,end=" ")
        print("\n")

        catog1 = input("Select your choice:\n").upper()
        print("")
        if catog1 == "A":
            print("Choose option for laptops:")
            print("(A)SORT BY BRANDS\t(B)GO BACK")
            print(" ")

            catog2 = input("Sort:\n").upper()
            print(" ")
            if catog2 == "A":
                print("(1)LENOVO")
                print("(2)APPLE")
                print("(3)ASUS")
                print(" ")


                catog3 = input("Choose Brand:\n").upper()
                print(" ")
                if catog3 == "1":
                    print("(1) Lenovo Ideapad 330 Core i3 7th Gen - (8 GB/1 TB HDD/Windows 10 Home)")
                    print("(2) Lenovo Thinpad E480 Core i3 7th Gen - (4 GB/500 GB HDD/Windows 10 Pro/512 MB Graphics)")
                    print("(3) Lenovo Ideapad 330s Core i3 7th Gen - (4 GB/1 TB HDD/Windows 10 Home)")
                    print("(4) Lenovo Yoga 520 Core i3 7th Gen - (4 GB/1 TB HDD/Windows 10 Home)")
                    print("(5) Lenovo Core i3 8th Gen - (8 GB/1 TB SSD/Windows 10 Home/2 GB Graphics)")

######################### LENOVO PRODUCT 1 spes ############################
                    catog4 = input("Choose Product:\n")
                    if catog4 == "1":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: Ideapad 330")
                        print("Color                \t: Platinum Grey")
                        print("Battery Backup       \t: Upto 6 hours")
                        print("Power Supply         \t: 45 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i3")
                        print("Processor Generation \t: 7th Gen")
                        print("RAM                  \t: 4GB DDR4")
                        print("HDD Capacity         \t: 1TB")
                        print("Clock Speed          \t: 2.3 Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED HD 602")
                        print("Number of cores      \t: 2")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 39.62cm (15.6 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print("Screen Type          \t: Full HD LEC Backlit Anti-glare TN Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: WIFI 1x1 AC")
                        print("Bluetooth            \t: v4.1")
                        print("Weight               \t: 2.2kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print("McAfee Livesafe 12 months subscription")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹43,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()
                        
######################### LENOVO PRODUCT 2 spes ############################
                    elif catog4 == "2":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: ThinkPad E480")
                        print("Color                \t: Black")
                        print("Battery Backup       \t: Upto 5 hours")
                        print("Power Supply         \t: 45 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i3")
                        print("Processor Generation \t: 7th Gen")
                        print("RAM                  \t: 4GB DDR4")
                        print("HDD Capacity         \t: 500 GB")
                        print("Clock Speed          \t: 2.3 Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("Dedicated Graphic Memory Capacity: 512 MB")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 pro")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 35.56cm (14 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: WIFI 1x1 802.11 a/b/g/n/ac")
                        print("Bluetooth            \t: v4.1")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹49,998")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()
                        
######################### LENOVO PRODUCT 3 spes ############################
                    elif catog4 == "3":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: Ideapad 330s")
                        print("Color                \t: Platinum Grey")
                        print("Battery Backup       \t: Upto 5 hours")
                        print("Power Supply         \t: 45 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i3")
                        print("Processor Generation \t: 7th Gen")
                        print("RAM                  \t: 4GB DDR4")
                        print("HDD Capacity         \t: 1TB")
                        print("Clock Speed          \t: 2.3 Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED HD 602")
                        print("Number of cores      \t: 2")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 39.62cm (15.6 inch)")
                        print("Screen Resolution    \t: 1366 x 768 pixel")
                        print("Screen Type          \t: Full HD LEC Backlit Anti-glare TN Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: WIFI 1x1 AC")
                        print("Bluetooth            \t: v4.1")
                        print("Weight               \t: 2.2kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹29,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### LENOVO PRODUCT 4 spes ############################
                    elif catog4 == "4":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: 2 in 1 Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: Yoga 520")
                        print("Color                \t: Mineral Grey")
                        print("Battery Backup       \t: Upto 10 hours")
                        print("Power Supply         \t: 45 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i3")
                        print("Processor Generation \t: 7th Gen")
                        print("RAM                  \t: 4GB DDR4")
                        print("HDD Capacity         \t: 1TB")
                        print("Clock Speed          \t: 2.3 Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED HD 602")
                        print("Number of cores      \t: 2")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 35.56(14 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print("Screen Type          \t: Full HD LEC Backlit Anti-glare TN Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: WIFI 1x1 AC")
                        print("Bluetooth            \t: v4.1")
                        print("Weight               \t: 2.2kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Web carmera")
                        print("McAfee Livesafe 12 months subscription")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹39,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()
                        
######################### LENOVO PRODUCT 5 spes ############################
                    elif catog4 == "5":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: 2 in 1 Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: Lenovo Core")
                        print("Color                \t: Platinum")
                        print("Battery Backup       \t: Upto 10 hours")
                        print("Power Supply         \t: 65 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i3")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR4")
                        print("SDD Capacity         \t: 1TB")
                        print("Clock Speed          \t: 2.9 Ghz with turbo clock speed 3.9Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("Dedicated memory capacity: 2GB")
                        print("NVIDIA GEFORCE MX230")
                        print("Number of cores      \t: 2")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 35.56cm (14 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print("Screen Type          \t: Full HD LEC Backlit Anti-glare TN Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: WIFI 1x1 AC")
                        print("Bluetooth            \t: v4.1")
                        print("Weight               \t: 1.56kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print("McAfee Livesafe 12 months subscription")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹82,190")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

                    else:
                        print("Invalid Choice")
                        chkcontinue1()


                elif catog3 == "2":
                    print("(1) Apple MacBook Air Core i5 8th Gen - (8 GB/256 GB SSD/Mac OS Mojave)")
                    print("(2) Apple MacBook Pro Core i5 8th Gen - (8 GB/128 GB SSD/Mac OS Mojave)")
                    print("(3) Apple MacBook Pro Core i5 8th Gen - (8 GB/256 GB SSD/Mac OS Mojave)")
                    print("(4) Apple MacBook Air Core i5 8th Gen - (8 GB/128 GB SSD/Mac OS Mojave)")
                    print("(5) Apple MacBook Core m3 7th Gen - (8 GB/256 GB SSD/Mac OS Mojave) ")

######################### APPLE PRODUCT 1 spes ############################
                    catog5 = input("Choose Product:\n")
                    if catog5 == "1":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: MacBook Air, 30 W Power Adapter, USB Type C Charge Cable (2 m), User Guide, Warranty Documents")
                        print("Series               \t: MacBook Air")
                        print("Color                \t: Silver")
                        print("Battery Backup       \t: Upto 13 hours")
                        print("Power Supply         \t: 30 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i5")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR3")
                        print("SSD Capacity         \t: 256GB")
                        print("Clock Speed          \t: 1.6 Ghz with turbo boost upto 3.6Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED UHD 617")
                        print("Number of cores      \t: 2")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: MAC OS Mojave")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 33.78cm (13.3 inch)")
                        print("Screen Resolution    \t: 2560 x 1600 Pixel")
                        print("Screen Type          \t: Quad HD LED Backlit IPS Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in three Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11a/b/g/n/ac")
                        print("Bluetooth            \t: v4.2")
                        print("Weight               \t: 1.25kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Polymer Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹1,04,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### APPLE PRODUCT 2 spes ############################                        
                    elif catog5 == "2":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: MacBook Pro, 61 W USB Type C Power Adapter, USB Type C Charge Cable (2 m), User Guide, Warranty Documents")
                        print("Series               \t: MacBook Pro")
                        print("Color                \t: Space Grey")
                        print("Battery Backup       \t: Upto 10 hours")
                        print("Power Supply         \t: 61 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i5")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR3")
                        print("SSD Capacity         \t: 128GB")
                        print("Clock Speed          \t: 1.4 Ghz with turbo boost upto 3.6Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED IRIS PLUS 645")
                        print("Number of cores      \t: 4")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: MAC OS Mojave")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 33.78cm (13.3 inch)")
                        print("Screen Resolution    \t: 2560 x 1600 Pixel")
                        print("Screen Type          \t: Quad HD LED Backlit IPS Retina Display (True Tone Technology, Wide Color (P3), 500 nits Brightness)")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in three Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11a/b/g/n/ac")
                        print("Bluetooth            \t: v5.0")
                        print("Weight               \t: 1.37kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Polymer Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹1,18,162")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### APPLE PRODUCT 3 spes ############################
                    elif catog5 == "3":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: MacBook Pro, 61 W USB Type C Power Adapter, USB Type C Charge Cable (2 m), User Guide, Warranty Documents")
                        print("Series               \t: MacBook Pro")
                        print("Color                \t: Silver")
                        print("Battery Backup       \t: Upto 10 hours")
                        print("Power Supply         \t: 61 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i5")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR3")
                        print("SSD Capacity         \t: 256GB")
                        print("Clock Speed          \t: 1.4 Ghz with turbo boost upto 3.6Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED IRIS PLUS 645")
                        print("Number of cores      \t: 4")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: MAC OS Mojave")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 33.78cm (13.3 inch)")
                        print("Screen Resolution    \t: 2560 x 1600 Pixel")
                        print("Screen Type          \t: Quad HD LED Backlit IPS Retina Display (True Tone Technology, Wide Color (P3), 500 nits Brightness)")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in three Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11a/b/g/n/ac")
                        print("Bluetooth            \t: v5.0")
                        print("Weight               \t: 1.37kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Polymer Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹1,36,204")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### APPLE PRODUCT 4 spes ############################
                    elif catog5 == "4":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: MacBook Air, 30 W USB Type C Power Adapter, USB Type C Charge Cable (2 m), User Guide, Warranty Documents")
                        print("Series               \t: MacBook Air")
                        print("Color                \t: Gold")
                        print("Battery Backup       \t: Upto 12 hours")
                        print("Power Supply         \t: 30 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i5")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR3")
                        print("SSD Capacity         \t: 128GB")
                        print("Clock Speed          \t: 1.6 Ghz with turbo boost upto 3.6Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED UHD 617")
                        print("Number of cores      \t: 2")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: MAC OS Mojave")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 33.78cm (13.3 inch)")
                        print("Screen Resolution    \t: 2560 x 1600 Pixel")
                        print("Screen Type          \t: Quad HD LED Backlit IPS Retina Display (True Tone Technology, Wide Color (P3), 500 nits Brightness)")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in three Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11a/b/g/n/ac")
                        print("Bluetooth            \t: v4.2")
                        print("Weight               \t: 1.25kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Polymer Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹94,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### APPLE PRODUCT 5 spes ############################
                    elif catog5 == "5":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: MacBook, 30 W USB Type C Power Adapter, USB Type C Charge Cable (2 m), User Guide, Warranty Documents")
                        print("Series               \t: MacBook")
                        print("Color                \t: Gold")
                        print("Battery Backup       \t: Upto 10 hours")
                        print("Power Supply         \t: 30 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core m3")
                        print("Processor Generation \t: 7th Gen")
                        print("RAM                  \t: 8GB DDR3")
                        print("SSD Capacity         \t: 256GB")
                        print("Clock Speed          \t: 1.2 Ghz with turbo boost upto 3Ghz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED HD 617")
                        print("Number of cores      \t: 2")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: MAC OS Mojave")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 30.48cm (12 inch)")
                        print("Screen Resolution    \t: 2304 x 1440 Pixel")
                        print("Screen Type          \t: Quad HD LED Backlit IPS Retina Display with True Tone Technology")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphone")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11ac")
                        print("Bluetooth            \t: v4.2")
                        print("Weight               \t: 0.92kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Polymer Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹89,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

                    elif catog5>"5":
                        print("Invalid Choice")
                        chkcontinue1()
                        

                elif catog3 == "3":
                    print("(1) Microsoft Surface Pro 6 Core i5 8th Gen - (8 GB/256 GB SSD/Windows 10 Home)")
                    print("(2) Microsoft Surface Pro 6 Core i5 8th Gen - (8 GB/128 GB SSD/Windows 10 Home)")
                    print("(3) Microsoft Surface Laptop 2 Core i5 8th Gen - (8 GB/128 GB SSD/Windows 10 Home)")
                    print("(4) Microsoft Surface Go Pentium Gold - (8 GB/128 GB SSD/Windows 10 Home in S Mode)")
                    print("(5) Microsoft Surface Pro Core m3 7th Gen - (4 GB/128 GB SSD/Windows 10 Pro)")

######################### ASUS PRODUCT 1 spes ############################
                    catog6 = input("Choose Product:\n")
                    if catog6 == "1":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: Asus Core")
                        print("Color                \t: Transparent Silver")
                        print("Battery Backup       \t: Upto 6 hours")
                        print("Power Supply         \t: 45 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i5")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR4")
                        print("SSD Capacity         \t: 512GB")
                        print("Clock Speed          \t: 1.6 GHz with Turbo Boost Upto 3.9 GHz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED UHD 620")
                        print("Number of cores      \t: 4")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 35.56 cm (14 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print("Screen Type          \t: Full HD LEC Backlit Anti-glare Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11ac")
                        print("Bluetooth            \t: v4.2")
                        print("Weight               \t: 1.6kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹46,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### ASUS PRODUCT 2 spes ############################
                    elif catog6 == "2":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: Laptop, Power Adaptor, User Guide")
                        print("Series               \t: Vivobook 15")
                        print("Color                \t: Peacock Blue")
                        print("Battery Backup       \t: Upto 6 hours")
                        print("Power Supply         \t: 45 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Ryzen 5 Quad Core")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR4")
                        print("SSD Capacity         \t: 512GB")
                        print("Clock Speed          \t: 2.0 GHz with Turbo Boost Upto 3.9 GHz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("AMD RADEON VEGA 8")
                        print("Number of cores      \t: 4")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 39.62 cm (15.6 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print("Screen Type          \t: 15.6 (16:9) LED-backlit FHD (1920x1080) 60Hz Anti-Glare Panel with 45% NTSC")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: Integrated 802.11ac (2x2)")
                        print("Bluetooth            \t: v4.0")
                        print("Weight               \t: 1.7kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹46,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### ASUS PRODUCT 3 spes ############################                        
                    elif catog6 == "3":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: Asus Core")
                        print("Color                \t: Slate Grey")
                        print("Battery Backup       \t: Upto 10 hours")
                        print("Power Supply         \t: 65 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i7")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR4")
                        print("SSD Capacity         \t: 512GB")
                        print("Clock Speed          \t: 1.8 GHz with Turbo Boost Upto 3.9 GHz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("NVIDIA GEFORCE MX230")
                        print("Number of cores      \t: 4")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 39.62 cm (15.6 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print("Screen Type          \t: Full HD LEC Backlit Anti-glare Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11ac")
                        print("Bluetooth            \t: v4.2")
                        print("Weight               \t: 1.9kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹62,399")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### ASUS PRODUCT 4 spes ############################
                    elif catog6 == "4":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: Asus Core")
                        print("Color                \t: Slate Grey")
                        print("Battery Backup       \t: Upto 6 hours")
                        print("Power Supply         \t: 45 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i3")
                        print("Processor Generation \t: 7th Gen")
                        print("RAM                  \t: 4GB DDR4")
                        print("SSD Capacity         \t: 256GB")
                        print("Clock Speed          \t: 2.3 GHz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("INTEL INTEGRATED HD 620")
                        print("Number of cores      \t: 2")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 39.62 cm (15.6 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print("Screen Type          \t: Full HD LEC Backlit Anti-glare Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11ac")
                        print("Bluetooth            \t: v4.2")
                        print("Weight               \t: 1.9kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹30,980")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

######################### ASUS PRODUCT 5 spes ############################
                    elif catog6 == "5":
                        print(" ")
                        print("Specifications!")
                        print("GENERAL:")
                        print("Sales Package        \t: Laptop, Power Adaptor, User Guide, Warranty Documents")
                        print("Series               \t: ZenBook 14")
                        print("Color                \t: Royal Blue")
                        print("Battery Backup       \t: Upto 6 hours")
                        print("Power Supply         \t: 65 W AC Adapter")
                        print(" ")
                        print("PROCESSOR AND MEMORY FEATURES:")
                        print("Process brand        \t: Intel")
                        print("Processor Name       \t: Core i5")
                        print("Processor Generation \t: 8th Gen")
                        print("RAM                  \t: 8GB DDR4")
                        print("SSD Capacity         \t: 512GB")
                        print("Clock Speed          \t: 1.6 GHz with Turbo Boost Upto 3.9 GHz")
                        print(" ")
                        print("GRAPHIC PROCESSOR")
                        print("NVIDIA Geforce MX250")
                        print("Number of cores      \t: 4")
                        print(" ")
                        print("OPERATING SYSTEM")
                        print("OS                   \t: Windows 10 Home")
                        print("OS Architecture      \t: 64 bit")
                        print(" ")
                        print("DISPLAY AND AUDIO FEATURES")
                        print("Touchscreen          \t: No")
                        print("Screen Size          \t: 35.56 cm (14 inch)")
                        print("Screen Resolution    \t: 1920 x 1080 pixel")
                        print("Screen Type          \t: Full HD LEC Backlit Anti-glare Display")
                        print(" ")
                        print("Built-in Dual Speakers")
                        print("Internal Mic")
                        print("Built-in Microphones")
                        print(" ")
                        print("CONNECTIVITY FEATURE")
                        print("Wireless LAN         \t: IEEE 802.11ac")
                        print("Bluetooth            \t: v5.0")
                        print("Weight               \t: 1.35kg")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Disk Drive           \t: Not Available")
                        print("CD/DVD writer")
                        print("Web carmera")
                        print(" ")
                        print("ADDITIONAL FEATURES")
                        print("Li-ion Battery")
                        print("Warranty")
                        print(" ")
                        print("WARRANTY SUMMARY")
                        print("1 Year Onsite Warranty")
                        print("Warranty Service type\t: Onsite/Covered in warranty")
                        print("Manafuacturing Defect\t: Covered in warranty")
                        print(" ")
                        print("NOT COVERED IN WARRANTY")
                        print("Physical Damage")
                        print("Domestic Warranty")
                        print("1 Year")
                        print(" ")
                        print("PRICE - ₹85,990")
                        print(" ")
                        print("(A)BUY\t(B)ADD TO CART")
                        buycart()

                    elif catog6>"5":
                        print("Invalid Choice")
                        chkcontinue1()
                    
                elif catog3>"3":
                    print("Invalid Choice")
                    chkcontinue1()                    

                else:
                    print("Invalid Selection!")
                    chkcontinue1()
                   
            elif catog2 == "B":
                ecommweb()    
                                        
            else:
                print("Invalid Selection!")
                chkcontinue1()
            
        elif catog1 == "B":
            print("Name:   \tManan Hakani")
            print("Email:  \tmananhakani@gmail.com")
            print("Phone:  \t9967250717")
            print("Address:\t1/B-104 Gokul Gaurav CHSL,")
            print("         \tShivaji Road Off M G Road,")
            print("         \tKandivali West Mumbai-400067")
            print("\n")
            chkcontinue1()

        else:
            print("invalid Selection!")
            chkcontinue1()
            
## WEBSITE/PRODUCT CODE END##
            
logincode()
